name = "schwafel-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-04-22"

[vars]
WORKERS_RS_VERSION = "0.0.9"
CORS_ORIGIN = "https://schwafel.app,https://schwafel.github.io,http://127.0.0.1:3000,http://localhost:3000"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
